- hosts: localhost

  tasks:
  - name: Test that my module works
    test: 
    register: result
    become: yes
    vars:
      ansible_python_interpreter: /usr/bin/python
  
  #outputs the ansible python version
  - debug: var=ansible_python_interpreter

  #outputs the module python version on the host
  - debug: var=result